-- Deputies (matching frontend/src/data/deputies.js)
INSERT INTO deputy (id, name, party, state, followed) VALUES
(1,  'Ana Souza',        'PSD',           'SP', true),
(2,  'Carlos Mendes',    'PT',            'RJ', true),
(3,  'Fernanda Lima',    'MDB',           'MG', false),
(4,  'Roberto Alves',    'PL',            'BA', true),
(5,  'Juliana Costa',    'PSOL',          'RS', false),
(6,  'Marcos Oliveira',  'PP',            'PR', true),
(7,  'Patricia Santos',  'PSDB',          'CE', false),
(8,  'Eduardo Silva',    'REPUBLICANOS',  'PE', true),
(9,  'Lucia Ferreira',   'PDT',           'SC', false),
(10, 'Ricardo Barbosa',  'UNIAO',         'GO', false);

-- Legislative Proposals (matching frontend/src/data/votes.js)
INSERT INTO legislative_proposal (id, title, summary, author, category, vote_date) VALUES
(1,  'PL 1234/2026 - Reforma Tributaria',
     'Simplifica o sistema tributario brasileiro, unificando cinco impostos em um unico Imposto sobre Bens e Servicos (IBS). Preve periodo de transicao de 7 anos e cashback para familias de baixa renda.',
     'Comissao Especial da Camara', 'Economia', '2026-03-25'),

(2,  'PL 567/2026 - Marco da Inteligencia Artificial',
     'Estabelece principios, direitos e deveres para o uso de inteligencia artificial no Brasil. Cria sistema de classificacao de risco e exige transparencia algoritmica em decisoes automatizadas.',
     'Dep. Fernanda Lima (MDB-MG)', 'Tecnologia', '2026-03-24'),

(3,  'PL 890/2026 - Piso Salarial da Enfermagem',
     'Reajusta o piso salarial dos profissionais de enfermagem para R$ 5.500 e define jornada maxima de 30 horas semanais. Inclui tecnicos e auxiliares com pisos proporcionais.',
     'Dep. Carlos Mendes (PT-RJ)', 'Saude', '2026-03-23'),

(4,  'PEC 45/2026 - Seguranca Publica',
     'Propoe a constitucionalizacao do Sistema Unico de Seguranca Publica (SUSP), com integracao das forcas policiais federais, estaduais e municipais e criacao de fundo nacional.',
     'Dep. Roberto Alves (PL-BA)', 'Seguranca', '2026-03-22'),

(5,  'PL 2345/2026 - Programa Escola Digital',
     'Universaliza o acesso a internet banda larga em todas as escolas publicas do pais e cria programa de distribuicao de tablets para alunos do ensino fundamental e medio.',
     'Dep. Juliana Costa (PSOL-RS)', 'Educacao', '2026-03-21'),

(6,  'PL 678/2026 - Protecao de Dados de Menores',
     'Proibe a coleta de dados pessoais de menores de 16 anos por plataformas digitais sem consentimento expresso dos responsaveis. Preve multas de ate 2% do faturamento.',
     'Dep. Patricia Santos (PSDB-CE)', 'Tecnologia', '2026-03-20'),

(7,  'PL 3456/2026 - Energia Renovavel',
     'Cria incentivos fiscais para empresas que investirem em energia solar e eolica. Reduz o ICMS sobre equipamentos de geracao distribuida e facilita financiamento para micro e pequenas empresas.',
     'Dep. Marcos Oliveira (PP-PR)', 'Meio Ambiente', '2026-03-19'),

(8,  'PL 4567/2026 - Combate as Fake News',
     'Obriga plataformas digitais a identificar e rotular conteudos gerados por IA, cria mecanismos de rastreabilidade de mensagens virais e estabelece responsabilidade das plataformas.',
     'Dep. Ana Souza (PSD-SP)', 'Comunicacao', '2026-03-18'),

(9,  'PL 5678/2026 - Moradia Popular',
     'Amplia o programa Minha Casa Minha Vida com nova faixa de renda e subsidios maiores. Inclui obrigatoriedade de areas verdes e equipamentos comunitarios nos empreendimentos.',
     'Dep. Eduardo Silva (REPUBLICANOS-PE)', 'Habitacao', '2026-03-17'),

(10, 'PL 6789/2026 - Transporte Publico Gratuito',
     'Institui a tarifa zero no transporte publico municipal para estudantes, idosos e pessoas com deficiencia. Cria fundo federal para compensar as empresas operadoras.',
     'Dep. Lucia Ferreira (PDT-SC)', 'Transporte', '2026-03-16'),

(11, 'PL 7890/2026 - Telemedicina',
     'Regulamenta a pratica da telemedicina no Brasil, permitindo consultas, diagnosticos e prescricoes remotas. Estabelece requisitos de seguranca digital e protecao de dados dos pacientes.',
     'Dep. Ricardo Barbosa (UNIAO-GO)', 'Saude', '2026-03-15'),

(12, 'PEC 12/2026 - Licenca Paternidade',
     'Amplia a licenca paternidade de 5 para 30 dias, com possibilidade de extensao para 60 dias em empresas do programa Empresa Cidada. Inclui pais adotivos e homoafetivos.',
     'Dep. Juliana Costa (PSOL-RS)', 'Trabalho', '2026-03-14'),

(13, 'PL 9012/2026 - Agrotoxicos',
     'Endurece as regras para registro e uso de agrotoxicos no Brasil. Proibe substancias banidas na Uniao Europeia e cria sistema de rastreabilidade do campo a mesa.',
     'Dep. Fernanda Lima (MDB-MG)', 'Meio Ambiente', '2026-03-13'),

(14, 'PL 1357/2026 - Startup Brasil',
     'Cria regime tributario simplificado para startups com faturamento de ate R$ 16 milhoes. Facilita contratacao de estrangeiros qualificados e cria visto especial para empreendedores.',
     'Dep. Ana Souza (PSD-SP)', 'Economia', '2026-03-12'),

(15, 'PL 2468/2026 - Saude Mental nas Escolas',
     'Torna obrigatoria a presenca de psicologos em todas as escolas publicas do pais. Cria programa de prevencao ao bullying e suicidio com capacitacao de professores.',
     'Dep. Carlos Mendes (PT-RJ)', 'Educacao', '2026-03-11');

-- Deputy Votes (150 records: 15 proposals x 10 deputies)
-- Distribution approximates frontend: ~45% SIM, ~35% NAO, ~10% ABSTENCAO, ~10% AUSENTE
INSERT INTO deputy_vote (deputy_id, proposal_id, vote) VALUES
-- Proposal 1: Reforma Tributaria
(1,  1, 'SIM'),
(2,  1, 'NAO'),
(3,  1, 'SIM'),
(4,  1, 'SIM'),
(5,  1, 'NAO'),
(6,  1, 'SIM'),
(7,  1, 'ABSTENCAO'),
(8,  1, 'SIM'),
(9,  1, 'NAO'),
(10, 1, 'AUSENTE'),
-- Proposal 2: Marco da IA
(1,  2, 'SIM'),
(2,  2, 'SIM'),
(3,  2, 'NAO'),
(4,  2, 'NAO'),
(5,  2, 'SIM'),
(6,  2, 'SIM'),
(7,  2, 'SIM'),
(8,  2, 'NAO'),
(9,  2, 'AUSENTE'),
(10, 2, 'SIM'),
-- Proposal 3: Piso Enfermagem
(1,  3, 'NAO'),
(2,  3, 'SIM'),
(3,  3, 'SIM'),
(4,  3, 'NAO'),
(5,  3, 'SIM'),
(6,  3, 'ABSTENCAO'),
(7,  3, 'SIM'),
(8,  3, 'SIM'),
(9,  3, 'NAO'),
(10, 3, 'SIM'),
-- Proposal 4: Seguranca Publica
(1,  4, 'SIM'),
(2,  4, 'NAO'),
(3,  4, 'SIM'),
(4,  4, 'SIM'),
(5,  4, 'NAO'),
(6,  4, 'SIM'),
(7,  4, 'NAO'),
(8,  4, 'AUSENTE'),
(9,  4, 'SIM'),
(10, 4, 'SIM'),
-- Proposal 5: Escola Digital
(1,  5, 'SIM'),
(2,  5, 'SIM'),
(3,  5, 'AUSENTE'),
(4,  5, 'NAO'),
(5,  5, 'SIM'),
(6,  5, 'NAO'),
(7,  5, 'SIM'),
(8,  5, 'SIM'),
(9,  5, 'SIM'),
(10, 5, 'NAO'),
-- Proposal 6: Protecao Dados Menores
(1,  6, 'SIM'),
(2,  6, 'SIM'),
(3,  6, 'SIM'),
(4,  6, 'NAO'),
(5,  6, 'SIM'),
(6,  6, 'SIM'),
(7,  6, 'ABSTENCAO'),
(8,  6, 'NAO'),
(9,  6, 'SIM'),
(10, 6, 'AUSENTE'),
-- Proposal 7: Energia Renovavel
(1,  7, 'NAO'),
(2,  7, 'SIM'),
(3,  7, 'SIM'),
(4,  7, 'SIM'),
(5,  7, 'NAO'),
(6,  7, 'SIM'),
(7,  7, 'SIM'),
(8,  7, 'SIM'),
(9,  7, 'ABSTENCAO'),
(10, 7, 'NAO'),
-- Proposal 8: Fake News
(1,  8, 'SIM'),
(2,  8, 'NAO'),
(3,  8, 'NAO'),
(4,  8, 'SIM'),
(5,  8, 'SIM'),
(6,  8, 'AUSENTE'),
(7,  8, 'SIM'),
(8,  8, 'NAO'),
(9,  8, 'SIM'),
(10, 8, 'SIM'),
-- Proposal 9: Moradia Popular
(1,  9, 'SIM'),
(2,  9, 'SIM'),
(3,  9, 'NAO'),
(4,  9, 'NAO'),
(5,  9, 'SIM'),
(6,  9, 'SIM'),
(7,  9, 'SIM'),
(8,  9, 'SIM'),
(9,  9, 'NAO'),
(10, 9, 'ABSTENCAO'),
-- Proposal 10: Transporte Gratuito
(1,  10, 'NAO'),
(2,  10, 'SIM'),
(3,  10, 'SIM'),
(4,  10, 'SIM'),
(5,  10, 'SIM'),
(6,  10, 'NAO'),
(7,  10, 'AUSENTE'),
(8,  10, 'SIM'),
(9,  10, 'SIM'),
(10, 10, 'SIM'),
-- Proposal 11: Telemedicina
(1,  11, 'SIM'),
(2,  11, 'SIM'),
(3,  11, 'SIM'),
(4,  11, 'NAO'),
(5,  11, 'ABSTENCAO'),
(6,  11, 'SIM'),
(7,  11, 'NAO'),
(8,  11, 'SIM'),
(9,  11, 'SIM'),
(10, 11, 'NAO'),
-- Proposal 12: Licenca Paternidade
(1,  12, 'SIM'),
(2,  12, 'SIM'),
(3,  12, 'NAO'),
(4,  12, 'SIM'),
(5,  12, 'SIM'),
(6,  12, 'NAO'),
(7,  12, 'SIM'),
(8,  12, 'AUSENTE'),
(9,  12, 'NAO'),
(10, 12, 'SIM'),
-- Proposal 13: Agrotoxicos
(1,  13, 'NAO'),
(2,  13, 'SIM'),
(3,  13, 'SIM'),
(4,  13, 'NAO'),
(5,  13, 'SIM'),
(6,  13, 'SIM'),
(7,  13, 'SIM'),
(8,  13, 'NAO'),
(9,  13, 'ABSTENCAO'),
(10, 13, 'SIM'),
-- Proposal 14: Startup Brasil
(1,  14, 'SIM'),
(2,  14, 'NAO'),
(3,  14, 'SIM'),
(4,  14, 'SIM'),
(5,  14, 'NAO'),
(6,  14, 'SIM'),
(7,  14, 'NAO'),
(8,  14, 'SIM'),
(9,  14, 'SIM'),
(10, 14, 'AUSENTE'),
-- Proposal 15: Saude Mental Escolas
(1,  15, 'SIM'),
(2,  15, 'SIM'),
(3,  15, 'AUSENTE'),
(4,  15, 'NAO'),
(5,  15, 'SIM'),
(6,  15, 'SIM'),
(7,  15, 'SIM'),
(8,  15, 'SIM'),
(9,  15, 'NAO'),
(10, 15, 'NAO');

-- Reset sequences
SELECT setval('deputy_id_seq', (SELECT MAX(id) FROM deputy));
SELECT setval('legislative_proposal_id_seq', (SELECT MAX(id) FROM legislative_proposal));
SELECT setval('deputy_vote_id_seq', (SELECT MAX(id) FROM deputy_vote));
